### ISSUE TITLE
Freeze after 3 pings

### ISSUE THREAD

**Issue by BorderCloud** [fetisov/lrndis#2]
Hello

I tested. I have a lot problems because my hardware is probably different and I'm again a newbie with these technologies.

For the newbie, can you add a tutorial or links for:
- Howto add correctly lib CMSIS and standard lib for a specific hardware STM32 ?
- Howto know if the hardware is correctly initialized ? (may be add a function for checking the hardware in mode debug)

Now for my problem, when I connect my card, I can see correctly the network card with the config dhcp on my pc but  I cannot see the website.

I try to ping the card. During the 2 first seconds, it works and after, the card is unresponsive.

Any idea ?

Thanks
Karima

**Comment by fetisov** [comment]
What happens after 2 seconds? Is the Hard fault happens? It is the known
bug and new version of library will be published at this month.
P.s. sorry for my English, I speak no very well.
11 авг. 2015 г. 12:05 пользователь "Karima Rafes" notifications@github.com
написал:

**Comment by BorderCloud** [comment]
No problem. I'm french and my english is also no very well ;)

I traced the problem. The program stops in the infinite loop in the file Interrupt.c (HardFault_Handler(void)).
The trace :
https://gist.github.com/BorderCloud/c11e968692c2c7341e72

**Comment by BorderCloud** [comment]
Here another test where I can ping  but when I try to open run.stm, the HardFault is thrown. The last line executed is in the file lwip-1.4.1\src\core\pbuf.c (details in the trace)
https://gist.github.com/BorderCloud/4fdcd551c604fb899b44

It's an error in the limit of my memory ?

**Comment by fetisov** [comment]
No. I think it is a problem of access to memory at unaligned address.
Please try to add
#define MEM_ALIGNMENT 4
in file lwipopts.h and do rebuild the project. I hope it solver the problem.
11 авг. 2015 г. 16:44 пользователь "Karima Rafes" notifications@github.com
написал:

**Comment by BorderCloud** [comment]
Cool ! It works. Perfect answer and great project.

Now, I can try to understand howto it works ;)

Bye
Karima
