### ISSUE TITLE
Issue for generating fsdata.c file

### ISSUE THREAD

**Issue by shravanprajapati122** [fetisov/lrndis#8]
I saw the usage of the makefsdata.c but can not understand, but your fsdata.c file is running in my code which directly generated the code from the stm32cubemx. using perl makefsdata.exe it create the array but server not running.
can you give me suggest how to use makefsdata.c to generate the fsdata.c??????

**Comment by fetisov** [comment]
Hello. makefsdata.c is the source code for the program that generates the fsdata.c file. There is already a compiled version of the program in the following path https://github.com/fetisov/lrndis/blob/master/makefsdata/htmlgen.exe. To prepare fsdata.c, you need to run the htmlgen program and specify the path to the directory with the html files of the project.
There is also a short instruction on how to compile a program using gcc:
https://github.com/fetisov/lrndis/blob/master/makefsdata/gcc-compile.bat
